# Site settings
baseURL = "//ecida.netlify.com"
languageCode = "en-US"
title = "ECiDA - Evolutionary Changes in Data Analysis"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2018 ECiDA Core Team"

[languages]
  [languages.en]
    weight = 1
  [languages.nl]
    weight = 2

[params]

  # Metadata for search engines and social sharing
  author = "ECiDA Core team"
  description = ""
  shareImage = "images/social.jpg"
  twitterHandle = ""

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/background.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "Code"
        url = "#"

      [[params.links.list1.link]]
        text = "Slack"
        url = "#"

      [[params.links.list1.link]]
        text = "Email"
        url = "#"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Partners"

      [[params.links.list2.link]]
        text = "Vitens"
        url = "#"

      [[params.links.list2.link]]
        text = "Anchormen"
        url = "#"

      [[params.links.list2.link]]
        text = "CWI"
        url = "#"

      [[params.links.list2.link]]
        text = "TNO"
        url = "#"

      [[params.links.list2.link]]
        text = "University of Groningen"
        url = "#"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Languagees"

      [[params.links.list3.link]]
        text = "Dutch"
        url = "/nl"

      [[params.links.list3.link]]
        text = "English"
        url = "/"


  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
